### ISSUE TITLE
QtCreator 4.3

### ISSUE THREAD

**Issue by l0mkaa** [rickytack/diagnostictools#3]
Вы планируете что нибудь делать дальше с этим проектом?
Не собирается для QtCreator 4.3
Сигналов
```
void runControlStarted(ProjectExplorer::RunControl *rc);
void runControlFinished(ProjectExplorer::RunControl *rc);
```
нет в projectexplorer.h
Сейчас там так
`signals:
    void finishedInitialization();

    // Is emitted when a project has been added/removed,
    // or the file list of a specific project has changed.
    void fileListChanged();

    void aboutToExecuteProject(ProjectExplorer::Project *project, Core::Id runMode);
    void recentProjectsChanged();

    void settingsChanged();

    void updateRunActions();`

**Comment by rickytack** [comment]
Хм, подумаю над этим

**Comment by rickytack** [comment]
А тут есть.(ветка 4.3) https://github.com/qtproject/qt-creator/blob/4.3/src/plugins/projectexplorer/projectexplorer.h
Если скачать исходники с https://www.qt.io/download-open-source/#section-2, то сигналы тоже на месте

**Comment by l0mkaa** [comment]
Ну да, Вы правы. Собралось и работает. Мой косяк.
